Use datetime.now(timestamp.utc) instead of datetime.utcnow() (#51, #52)
This fixes the following error:

TypeError: can't compare offset-naive and offset-aware datetimes